---
- name: Restore playbook.yml
  hosts: all
  tasks:
    - name: 1) 패키지 삭제 - httpd, mariadb-server, php, mutt
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: absent
      vars:
        packages:
          - httpd
          - mariadb-server
          - php
          - mutt
