---
- name: 1. 관리 대상 호스트 PowerOFF
  hosts: ansible1, ansible2, ansible3, ansible4
  gather_facts: false
  tasks:
    - name: 1) 전원 끄기
      community.general.shutdown:
        delay: 0
      ignore_errors: true
