---
# tasks file for myfirewall
- name: 패키지 설치 - firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: 서비스 기동 - firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: 포트 등록 - http, https
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop: "{{ fw_svc }}"
