---
- name: 0) 준비 작업 - 사용자 정의 facts 준비
  ansible.builtin.import_playbook: setup_facts.yml

- name: 2. 변수 테스트
  hosts: lamp
  vars_files:
    - vars/main.yml
  vars:
    firewall: firewalld
  tasks:
    ####################################
    # 1) 패키지 설치 - mariadb-server, httpd
    # 2) 서비스 기동 - mariadb, httpd
    # 3) 서비스 설정
    #     * /var/www/html/index.html
    # 4) 방화벽 포트 등록
    #     * 방화벽 패키지 설치
    #     * 방화벽 서비스 기동
    #     * 방화벽 포트 등록
    ####################################
    - name: 1) 방화벽 포트 삭제 - 방화벽 포트 삭제
      ansible.posix.firewalld:
        service: "{{ fw_port }}"
        permanent: false
        immediate: false
        state: disabled
      ignore_errors: true

    - name: 2) 서비스 종료 - firewalld, mariadb, httpd
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop:
        - "{{ firewall }}"
        - "{{ ansible_local.custom.services.db_service }}"
        - "{{ ansible_local.custom.services.web_service }}"

    - name: 3) 서비스 설정 삭제 - /var/www/html/index.html
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 1) 서비스 패키지 삭제 - mariadb-server, httpd
      ansible.builtin.dnf:
        name:
          - "{{ ansible_local.custom.packages.db_package }}"
          - "{{ ansible_local.custom.packages.web_package }}"
        state: absent

    - name: 3) 사용자 정의 팩트 파일 삭제 - /etc/ansible/facts.d
      ansible.builtin.file:
        path: /etc/ansible/facts.d
        state: absent
