---
- name: 0) 작업 제어 실습
  hosts: webservers
  gather_facts: true
  vars_files:
    - vars/vars.yml
  tasks:
    ##############################################
    # 0) 점검 - MEM > 256, 배포판: CentOS
    # 1) 패키지 설치 - httpd, mod_ssl, firewalld
    # 2) 서비스 기동 - httpd, firewalld
    # 3) 웹 서버 설정(notify)
    #   * /etc/pki/tls/certs/localhost.crt
    #   * /etc/pki/tls/private/localhost.key
    #   * /var/www/html/index.html
    # 4) 방화벽 포트 등록 - http, https
    # 5) handlers 정의
    ##############################################
    - name: Block when 사용
      block:
        - name: 1) 패키지 설치 - {{ packages }}
          ansible.builtin.dnf:
            name: "{{ packages }}"
            state: present

        - name: 2) 서비스 기동 - {{ services }}
          ansible.builtin.systemd:
            name: "{{ item }}"
            enabled: true
            state: started
          loop: "{{ services }}"

        - name: Block ~ Rescue
          block:
            - name: 3) 웹 서버 설정
              # * /etc/pki/tls/certs/localhost.crt
              # * /etc/pki/tls/private/localhost.key
              # * /var/www/html/index.html
              ansible.builtin.copy:
                src: "{{ item.src }}"
                dest: "{{ item.dest }}"
                owner: "{{ item.owner }}"
                group: "{{ item.group }}"
                mode: "{{ item.mode | string }}"
              loop: "{{ web_config_files }}"
              notify: Restart_web_service
          rescue:
            - name: 3) 웹 서버 설정 - 에러메세지 출력
              ansible.builtin.debug:
                msg: "[ FAIL ] 웹 서버 설정이 잘못 되었습니다."

        - name: 4) 방화벽에 포트 등록
          ansible.posix.firewalld:
            service: "{{ item }}"
            permanent: true
            immediate: true
            state: enabled
          loop: "{{ firewall_rules }}"
      when: |
        ansible_memtotal_mb > min_ram_mb or
        ansible_distribution == "CentOS" or
        ansible_distribution_version == "9"

  handlers:
    - name: Restart_web_service
      ansible.builtin.systemd:
        name: "{{ web_service }}"
        state: restarted
