---
- name: 파일 서버 설정
  hosts: fileservers
  tasks:
    - name: 1) 변수 포함
      ansible.builtin.include_vars: paths.yml

    - name: 2) 테스트 디렉토리 생성 - "{{ paths['fileserver'] }}"
      ansible.builtin.file:
        path: "{{ paths['fileserver'] }}"
        state: directory
        owner: root
        group: root
        mode: '0755'
      register: output

    - name: 변수 내용 출력
      ansible.builtin.debug:
        var: output.path
