---
- name: 1. 파일 서버 패키지 설치
  hosts: fileservers
  tasks:
    - name: 1) 변수 포함
      ansible.builtin.include_vars: package.yml

    - name: 2) 패키지 삭제 task
      ansible.builtin.include_tasks: remove_packages.yml
      vars:
        package:
          - httpd
          - tomcat

    - name: 3) 변수 포함
      ansible.builtin.include_vars: paths.yml

    - name: 4) 디렉 삭제
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ paths.fileserver }}"
        - "{{ paths.dbpath }}"
