---
- name: 1. 사용자 추가 - developer
  hosts: all
  vars_files:
    - secret.yml
  tasks:
    ##########################
    # 1) 사용자 추가
    # * ID/PASS: deveploper/developer
    # * 키배포: authorized_keys
    # * /etc/sudoers.d/developer
    # 2) 사용자 환경 세팅
    # * ~/.bashrc
    # * ~/.local/share/ble.sh
    ##########################
    - name: 1) 사용자 추가
      ansible.builtin.user:
        user: "{{ username }}"
        password: "{{ pwhash | password_hash('sha512') }}"

    - name: 2) 키 배포
      ansible.posix.authorized_key:
        user: developer
        state: present
        key: "{{ lookup('file', 'home/ansible/.ssh/id_rsa.pub') }}"

    - name: 3) /etc/sudoers.d/developer 파일 생성
      ansible.builtin.copy:
        src: files/developer
        dest: /etc/sudoers.d/developer
        owner: root
        group: root
        mode: '0440'

    - name: 4) 환경 설정 - $HOME/.bashrc
      ansible.builtin.template:
        src: templates/bashrc.j2
        dest: home/developer/.bashrc
        owner: developer
        group: developer
        mode: '0644'

    - name: 5) 환경 설정 - ble.sh
      ansible.builtin.copy:
        src: files/blesh
        dest: /home/developer/.local/share/
        owner: developer
        group: developer
