---
- name: Install and start Apache HTTPD
  hosts: all
  tasks:
    - name: 5) Configuration firewall
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled

    - name: 3) httpd is started
      ansible.builtin.service:
        name: httpd
        state: stopped
        enabled: false

    - name: 2) Correct index.html is present
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: 4) 패키지 삭제
      ansible.builtin.yum:
        name: httpd
        state: absent
