---
- name: Restore playbook
  hosts: databases
  vars:
    web_package: httpd
    db_package: mariadb-server
    db_service: mariadb
  tasks:
    - name: Stop {{ db_service }} service
      ansible.builtin.service:
        name: "{{ db_service }}"
        state: stopped

    - name: Remove {{ db_package }} and {{ web_package }}package
      ansible.builtin.yum:
        name:
          - "{{ web_package }}"
          - "{{ db_package }}"
        state: absent
