---
- name: 1. DB 작업
  hosts: databases
  remote_user: root
  gather_facts: false
  vars:
    pkg_db:
      - mariadb-server
      - mariadb
      - python-PyMySQL
    svc_db: mariadb
    url: http://ansible.example.com
  tasks:
    ############################
    # 1) DB 패키지 설치 - mariadb-server, mariadb, python-PyMySQL
    #     -> nofigy "set db password"
    # 2) DB 서비스 기동 - mariadb
    # 3) DB 설정 - /etc/my.cnf(ansible:/var/www/html/my.cnf.standard)
    #     -> notify "restart db service"
    ############################
    - name: 1) DB 패키지 설치
      ansible.builtin.yum:
        name: "{{ pkg_db }}"
        state: present
      notify:
        - Set db password

    - name: 2) 서비스 기동
      ansible.builtin.service:
        name: "{{ svc_db }}"
        state: started
        enabled: true

    - name: 3) DB 설정 - /etc/my.cnf
      ansible.builtin.get_url:
        url: "{{ url }}/my.cnf.standard"
        dest: /etc/my.cnf
        owner: root
        group: root
        mode: '0644'
        force: true
      notify:
        - Restart db service

  handlers:
    - name: Set db password
      community.mysql.mysql_user:
        # root@'%' => All privileges
        name: root
        password: soldesk1.
        priv: '*.*:ALL'
        state: present

    - name: Restart db service
      ansible.builtin.service:
        name: "{{ svc_db }}"
        state: restarted
