---
- name: 1. DB 작업
  hosts: databases
  remote_user: root
  gather_facts: false
  vars:
    pkg_db:
      - mariadb-server
      - mariadb
      - python-PyMySQL
    svc_db: mariadb
    url: http://ansible.example.com
  tasks:
    ############################
    # 1) 서비스 중지 - mariadb
    # 2) DB 패키지 삭제 - mariadb-server, mariadb, python-PyMySQL
    ############################
    - name: 2) 서비스 중지
      ansible.builtin.service:
        name: "{{ svc_db }}"
        state: stopped
        enabled: false

    - name: 1) DB 패키지 삭제
      ansible.builtin.yum:
        name: "{{ pkg_db }}"
        state: absent
