---
- name: SELinux mode change
  hosts: all
  gather_facts: false
  tasks:
    - name: SELinux 모드 변경; permissive -> enforcing
      ansible.posix.selinux:
        policy: targeted
        state: enforcing

    # - name: 1)
    #   ansible.builtin.lineinfile:
    #     path: /etc/selinux/config
    #     regexp: '^SELINUX='
    #     line: 'SELINUX=permissive'

    # - name: 2)
    #   ansible.builtin.command: setenforce 0
