---
- name: Restore intranet.yml
  hosts: all
  tasks: 
    ############################################
    # 1) 패키지 설치 - httpd, firewalld(dnf)
    # 2) 웹서버 설정 - /var/www/html/index.html(copy)
    # 3) 서비스 기동 - httpd, firewalld(systemd)
    # 4) 방화벽 등록 - http(firewalld)
    #############################################
    - name: 1) 방화벽 등록 해제 - http(firewalld)
      ansible.posix.firewalld:
        service: http
        permanent: true
        immediate: true
        state: disabled

    - name: 2) 서비스 기동 해제 - httpd, firewalld(systemd)
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: stopped
        enabled: false
      loop: 
        - httpd
        - firewalld

    - name: '3) /var/www/html/index.html(file) 파일 삭제'
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent


    - name: '4) 패키지 삭제 - httpd'
      ansible.builtin.dnf:
        name: httpd
        state: absent
