---
- name: 1. DB 서비스 기동 - 반복문 테스트
  hosts: database_prod
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
      - mariadb
    db_svc: mariadb
  tasks:
    #############################
    # 1) 패키지 설치 - mariadb-server, python3-PyMySQL, mariadb
    # 2) DB 서비스 기동 - mariadb
    #############################
    - name: 1) 패키지 설치
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop: "{{ db_packages }}"
      when: ansible_distribution == "RedHat"

    - name: DB 서비스 기동 - mariadb
      ansible.builtin.systemd:
        name: "{{ db_svc }}"
        state: started
        enabled: true
