---
- name: Restore_playbook
  hosts: all
  vars:
    db_packages:
      - mariadb-server
      - python3-PyMySQL
      - mariadb
    db_svc: mariadb
  tasks:
    #############################
    # 2) DB 서비스 종료 - mariadb
    # 1) 패키지 설치 - mariadb-server, python3-PyMySQL, mariadb
    #############################
    - name: 1) DB 서비스 종료 - mariadb
      ansible.builtin.systemd:
        name: "{{ db_svc }}"
        state: stopped
        enabled: false

    - name: 2) DB 패키지 삭제
      ansible.builtin.dnf:
        name: "{{ db_packages }}"
        state: present
      when: ansible_distribution == "CentOS"
